### ISSUE TITLE
tgui gulp flow is broken

### ISSUE THREAD

**Issue by karlnp** [tgstation/tgstation#22202]
When running `build_assets.bat`, 

```
λ build_assets.bat
node.js and all dependencies must be installed for this script to work.
If this script fails try installing dependencies again.
[16:02:58] Requiring external module babel-register
[16:03:06] Using gulpfile ~\Documents\GitHub\tgstation\tgui\gulpfile.babel.js
[16:03:06] Starting 'default'...
[16:03:06] Starting 'css'...
[16:03:06] Starting 'js'...
[16:03:11] tgui.css saved 5.17 KB (39.78 KB -> 34.61 KB)
[16:03:11] Finished 'css' after 5.03 s
resolve failed:  { Error: Cannot find module 'paths-js'
    at Function.Module._resolveFilename (module.js:469:15)
   [stack omitted]
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } paths-js
resolve failed:  { Error: Cannot find module 'caniuse-db'
    at Function.Module._resolveFilename (module.js:469:15)
       [stack omitted]
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } caniuse-db
resolve failed:  { Error: Cannot find module 'babel-runtime'
    at Function.Module._resolveFilename (module.js:469:15)
     [stack omitted]
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } babel-runtime
[16:03:33] tgui.js saved 483.56 KB (1005.27 KB -> 521.71 KB)
[16:03:33] Finished 'js' after 27 s
[16:03:33] Starting 'size'...
[16:03:33] all files 1.33 MB
[16:03:33] Finished 'size' after 116 ms
[16:03:33] Finished 'default' after 27 s
Press any key to continue . . .
```

These errors do not actually result in any problems in my simple testing of tgui (while trying to make a fancy vending machine interface), but they will mislead people. I'm not actually sure what Browserify is doing here anyway, or why it's needed beyond polyfills. Additionally large parts of the tgui package.json dependencies are outdated, but I believe Mervill is working on that.

When I brought this up in #coderbus a couple days ago, it ended up with people suggesting we throw out tgui entirely, adopt nanoui, prototype a purely DM approach, and a few other things. Nobody seems happy with having to use IE except for that one guy who was playing on an ancient XP box. 

At the very least, I believe the iteration flow for  tgui can be streamlined and simplified, and these errors can likely be removed with little effort.

**Comment by optimumtact** [comment]
keep the backend byond code for tgui, replace the templating front end with doT.js again
http://olado.github.io/doT/index.html

nanoui used it and it was a great choice, it was reasonably fast, very little dependencies and still offered quite a few features.

**Comment by Mervill** [comment]
Can we do that without rewriting every tgui? That's the approach I'm trying to take right now

**Comment by optimumtact** [comment]
no

**Comment by Mervill** [comment]
For the record: all the uncertainty around tgui's pipeline is preventing from moving forward with a bunch of UI updates. If I have to rewrite the UI in two weeks I'll just wait till then.

**Comment by optimumtact** [comment]
The likelihood of anyone making changes to the TGUI's is practically zero.

The reason why we have so many is because nobody actually wants to maintain the ui's

Feel free to proceed.

**Comment by optimumtact** [comment]
To be more specific, any change to the UI will require ripping out the following

All remaining nanoui code (if any exists)
The html_ui that nullquery developed (and is only used for cards and crew monitor (iirc))

It will also require replacing all existing tgui's with the new ui.

Therefore it's extremely likely that we will remain on tgui as our codebase standard.

**Comment by Cyberboss** [comment]
This was fixed at some point @lzimann
