### ISSUE TITLE
Building tgui has become impossible.

### ISSUE THREAD

**Issue by DaxDupont** [tgstation/tgstation#37949]
Building tgui is impossible, it keeps throwing errors even with dependencies installed.

I'm guessing packages started breaking because we're using packages that are years out of date.
```
node.js and all dependencies must be installed for this script to work.
If this script fails try installing dependencies again.
[16:27:36] Requiring external module @babel/register
D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-descriptors.js:162
    throw new Error(`Plugin/Preset files are not allowed to export objects, only functions. In ${filepath}`);
    ^

Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\tg\tgstation\tgui\node_modules\babel-preset-es2015\lib\index.js
    at createDescriptor (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-descriptors.js:162:11)
    at items.map (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-descriptors.js:87:50)
    at Array.map (<anonymous>)
    at createDescriptors (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-descriptors.js:87:29)
    at createPresetDescriptors (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-descriptors.js:79:10)
    at presets (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-descriptors.js:61:19)
    at presets (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-descriptors.js:51:25)
    at mergeChainOpts (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-chain.js:308:26)
    at D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-chain.js:271:7
    at buildRootChain (D:\tg\tgstation\tgui\node_modules\@babel\core\lib\config\config-chain.js:119:22)
```

D:\tg\tgstation\tgui>npm --version
6.0.1

D:\tg\tgstation\tgui>node --version
v8.11.2

**Comment by DaxDupont** [comment]
@MrStonedOne

**Comment by DaxDupont** [comment]
I THINK its because dependencies installs the latest gulp, installing the version from the package.json seemed to work.

**Comment by pubby** [comment]
I ran into this too

**Comment by DaxDupont** [comment]
@pubby when

**Comment by pubby** [comment]
a week ago I couldn't fix it

**Comment by ike709** [comment]
This sounds like the perfect time to shill Oracle UI, which you don't even need to build and doesn't require node: https://github.com/OracleStation/OracleStation/pull/702

**Comment by SpaceManiac** [comment]
Works for me, modulus warnings.
```
$ node --version
v8.10.0

$ npm --version
6.0.1

$ gulp --version
[12:25:59] CLI version 2.0.1

$ npm i
npm WARN deprecated babel-preset-es2015@6.24.1: �  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 17 packages from 9 contributors, removed 49 packages and updated 33 packages in 117.102s
[!] 22 vulnerabilities found [7026 packages audited]
    Severity: 7 Low | 3 Moderate | 11 High | 1 Critical
    Run `npm audit` for more detail

$ gulp --min
[12:26:02] Failed to load external module @babel/register
[12:26:02] Requiring external module babel-register
[12:26:20] Using gulpfile D:\projects\tgstation\tgui\gulpfile.babel.js
[12:26:20] Starting 'default'...
[12:26:20] Starting 'css'...
[12:26:20] Starting 'js'...
[12:26:31] tgui.css saved 5.33 KB (40.83 KB -> 35.5 KB)
[12:26:31] Finished 'css' after 10 s
[12:26:42] tgui.js saved 498.45 KB (1.06 MB -> 591.79 KB)
[12:26:42] Finished 'js' after 22 s
[12:26:42] Starting 'size'...
[12:26:43] all files 1.4 MB
[12:26:43] Finished 'size' after 1.34 s
[12:26:43] Finished 'default' after 23 s
```

**Comment by MrStonedOne** [comment]
@ike709 

We can't use oracle ui because it redraws the entire dom on updates, destroying any state. So if you have a text box, all text in it gets cleared on updates, if you have a canvas running a animated graph, that graph will reset on updates rather then keeping state, etc. 

A better bet would be helping me finish dm template.

**Comment by XDTM** [comment]
worked for me a few days ago, but i had to install an earlier version of node.js

**Comment by ShizCalev** [comment]
@XDTM what version?
