### ISSUE TITLE
ran into a problem with tgui

### ISSUE THREAD

**Issue by InTroubleWh** [tgstation/tgstation#51068]
## Reproduction: my TGUI crashed and showed this.
TypeError: Unable to get property 'path' of undefined or null reference
   at Anonymous function (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:471406)
   at Anonymous function (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:17878)
   at map (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:146805)
   at t.MiningVendor (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:470588)
   at Anonymous function (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:205820)
   at Anonymous function (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:205790)
   at Se (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:205768)
   at Anonymous function (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:207473)
   at Pe (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:207342)
   at Re (http://127.0.0.1:49891/tmp4932/tgui.bundle.js:1:212649)

**Comment by kriskog** [comment]
@stylemistake during the testmerge

**Comment by kriskog** [comment]
Closing as its related to testmerge
