### ISSUE TITLE
Blue screen error on vendors and computer consoles

### ISSUE THREAD

**Issue by PauliHuxfiel** [tgstation/tgstation#52257]
## Reproduction:
Vendor and computer consoles show a blue screen with the following error. It's been happening ever since june 14th. Tried closing the client, reinstalling BYOND and disabling firewall but nothing's worked so far. Only occurs on Manuel, Sybil seems fine.  Lathe interfaces work fine too.

Error: 8e5e0247.
   at Anonymous function (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:252823)
   at n (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:98)
   at Anonymous function (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:96968)
   at n (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:98)
   at Anonymous function (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:137895)
   at n (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:98)
   at Anonymous function (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:136286)
   at n (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:98)
   at Anonymous function (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:905)
   at Global code (http://127.0.0.1:65019/tmp11460/tgui.bundle.js:1:2)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; HPDTDF; BRI/2; .NET4.0E; .NET4.0C)

**Comment by Angustmeta** [comment]
Do you have different "tgui Style" settings on Manuel and Sybil?

**Comment by PauliHuxfiel** [comment]
I'm not sure, I don't think so. Sorry, this might be a dumb question but where can I find the tgui style settings?

**Comment by Angustmeta** [comment]
![200715 1430 29](https://user-images.githubusercontent.com/46400996/87545160-d4306180-c6a7-11ea-8d18-57f72b264191.png)

I've had issues before when it was set to "no frills", but not the same issue as this one.

**Comment by PauliHuxfiel** [comment]
The "UI style" and "tgui style" are the same on both servers. But the Sybil game preferences show a setting for "tgui monitors". This setting however does not appear on Manuel. 
![image](https://user-images.githubusercontent.com/68303781/87550044-e1048380-c6ae-11ea-8506-4c5176d9325e.png)

**Comment by PauliHuxfiel** [comment]
Well the bug was resolved for a couple of days but since today I'm having the issue on all tg servers.
