### ISSUE TITLE
tgui: Orbit BSOD during iteration

### ISSUE THREAD

**Issue by Slow-th** [tgstation/tgstation#53671]
Got a fancy blue screen of death and it told me to do some crap here but I ain't no Github pro

```
TypeError: Unable to get property 'Symbol(Symbol.iterator)_a.durvp6qoa1k' of undefined or null reference
   at d (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:607469)
   at t.Orbit (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:609532)
   at Anonymous function (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:208414)
   at Anonymous function (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:208384)
   at Le (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:208362)
   at Anonymous function (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:208304)
   at Le (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:208246)
   at je (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:215510)
   at De (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:215749)
   at Anonymous function (http://127.0.0.1:55978/tmp13260/tgui.bundle.js:1:138516)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
```

![image](https://user-images.githubusercontent.com/35464665/93008561-0b49b480-f52b-11ea-9e75-4948338be3e4.png)

**Comment by Couls** [comment]
What machine were you using?

**Comment by stylemistake** [comment]
Looks like it happened in Orbit UI in some iterator, he has IE11 and Windows 8 or later.

**Comment by Barhandar** [comment]
Round ID: 146241 (/tg/Station Sybil [ENGLISH] [US-WEST] [100% LAG FREE])
```
'undefined' is null or not an object
   at https://tgstation13.download/byond/assets/b8/asset.b8957a49d3bfaac7ced31e2833e1877f.js:1
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; byond_4.0; byond_5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Creative AutoUpdate v1.40.01)
Object doesn't support this property or method
   at http://127.0.0.1:11353/tmp4840/tgui-window-1.html:1
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/4.0; byond_4.0; byond_5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C; .NET4.0E; Creative AutoUpdate v1.40.01)
```

**Comment by jlsnow301** [comment]
Orbit has faced some heavy rewrites and this has not been resubmitted as an issue. Probably fine, feel free to reopen this if it isn't
