### ISSUE TITLE
TGUI bluescreening on everything, persistent after byond restart and even cache clear.

### ISSUE THREAD

**Issue by OmegaDarkPotato** [tgstation/tgstation#53997]
## Reproduction: 
Really just opening any tgui caused a [bluescreen](https://cdn.discordapp.com/attachments/543879244594413618/759606310709887006/unknown.png). I tried to work with armhulen, who was on at the time, through an F5 on the screen, closing and re-opening the client, and even a cache clear - all of which failed. He requested that I set my AI appearance to the custom one (see: AI custom appearance/portrait), which again brought up yet another bluescreen. Unknown if it was related or not.

**Comment by optimumtact** [comment]
@stylemistake any thoughts?

**Comment by stylemistake** [comment]
I have no idea whatsoever, but I suspect that CDN is the primary cause of this, because it does not happen locally (unless proven otherwise).

**Comment by OmegaDarkPotato** [comment]
Attempted a re-install of byond today, and played on bagil as well, same testmerge was in on bagil (if that's relevant) and I still got the same bluescreen error. I don't think it's anything that's byond's fault at least. In addition, I'm pretty sure I was fine up until that testmerge happened on sybil, so perhaps there's something between the two.

**Comment by OmegaDarkPotato** [comment]
Well I connected again and it's mysteriously fixed - will continue playing to see if this is fixed for multiple rounds or not, but I can once again see tgui things. Strange.

**Comment by optimumtact** [comment]
@MrStonedOne for CDN issues

**Comment by MrStonedOne** [comment]
We already do max cors allow.

Next time this reproduces, can you have an online admin hit disable-cdn in the server tab then close and re-open the game and tell me if that changes anything.

You can link them to this comment if they have reservations about hitting the button.

**Comment by stylemistake** [comment]
> Next time this reproduces, can you have an online admin hit disable-cdn in the server tab then close and re-open the game and tell me if that changes anything.

Armhulen tried this yesterday, and disabling CDN fixes it.

**Comment by Cyprex** [comment]
#54047
Different issue, however also fixed by disabling the CDN. Related?

**Comment by stylemistake** [comment]
CC: @Cyprex @Wolter-Lin @kopoba

This issue is **very** related and is very frequent.

Notes from #54047:

> Sybil has nothing testmerged right now but does not work. Campbell, which is on the same commit as Sybil, DOES however work. Very odd.

> Toggling CDN fixes things immediately without reconnecting.

**Comment by optimumtact** [comment]
@MrStonedOne PLS

**Comment by MrStonedOne** [comment]
I've disabled auto-static-gzip at the server side for new assets and im gonna purge the asset store and cloudflare cache here in a bit.

What I think might be happening is for new versions of tgui, it's getting gzipped twice at the same time, and this is producing a broken response that can't be decompressed by ie because gzip wrote to the file from two different threads.

If this doesn't work i'll try disabling cloudflare and enabling additional logging at nginx's side.

**Comment by optimumtact** [comment]
Thanks very much

**Comment by Cyprex** [comment]
No difference for me so far on Terry.

**Comment by MrStonedOne** [comment]
@Cyprex I changed the url so that local cache would also be invalidated. It would seem odd for IE to cache an invalid response, but it's also IE so that would be on brand.

Try again?

**Comment by Cyprex** [comment]
No difference for me on Terry, I tried making a new wineprefix as well, no difference.

**Comment by stylemistake** [comment]
^ Fresh reports.

**Comment by Mooshimi** [comment]
```

ooooo      ooo     .     .oooooo.    .oooooo..o
`888b.     `8'   .o8    d8P'  `Y8b  d8P'    `Y8
 8 `88b.    8  .o888oo 888      888 Y88bo.
 8   `88b.  8    888   888      888  `"Y8888o.
 8     `88b.8    888   888      888      `"Y88b
 8       `888    888 . `88b    d88' oo     .d8P
o8o        `8    "888"  `Y8bood8P'  8""88888P'

 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error.
   at https://tgstation13.download/byond/assets/86/asset.8614c204a358b39d682c395cd7eb7797.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; Zoom 3.6.0)

Nanotrasen (c) 2525-2562 
 
```

The chat window is the location of this error I got just now.

**Comment by Mooshimi** [comment]
#67839
#67840

**Comment by Mooshimi** [comment]
`       
 

ooooo      ooo     .     .oooooo.    .oooooo..o
`888b.     `8'   .o8    d8P'  `Y8b  d8P'    `Y8
 8 `88b.    8  .o888oo 888      888 Y88bo.
 8   `88b.  8    888   888      888  `"Y8888o.
 8     `88b.8    888   888      888      `"Y88b
 8       `888    888 . `88b    d88' oo     .d8P
o8o        `8    "888"  `Y8bood8P'  8""88888P'

 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 Script error.
   at https://tgstation13.download/byond/assets/86/asset.8614c204a358b39d682c395cd7eb7797.js:0
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0; Zoom 3.6.0)

Nanotrasen (c) 2525-2562 
 `

another error from today

**Comment by Follint** [comment]
I'm having absolutely the same issue, no recommendations have done anything so far. I've updated every browser I have, cleared every cache, byond, browser, dreamdeamon and so on, reinstalled byond multiple times, and still getting about the same error when trying to load fancy chat on any server, tg or otherwise. Absolutely no clue what to do now besides total OS reinstall. On my laptop chat seems to work just fine tho. I'm certain this is a local machine issue, but I have no hope of troubleshooting this so... Posting in this megaissue is my best bet i guess, hovewer old this is. I'm getting pretty desperate to fix this tbh.


```
ooooo      ooo     .     .oooooo.    .oooooo..o
`888b.     `8'   .o8    d8P'  `Y8b  d8P'    `Y8
 8 `88b.    8  .o888oo 888      888 Y88bo.
 8   `88b.  8    888   888      888  `"Y8888o.
 8     `88b.8    888   888      888      `"Y88b
 8       `888    888 . `88b    d88' oo     .d8P
o8o        `8    "888"  `Y8bood8P'  8""88888P'
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation.

TypeError: t.startsWith is not a function
    at lE (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:347549)
    at t.value (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:360528)
    at t.value (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:354941)
    at t.value (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:354766)
    at n.value (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:364720)
    at at (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:93170)
    at ad (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:102881)
    at at (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:93633)
    at ad (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:102881)
    at at (http://127.0.0.1:50452/asset.8e0b31e673ee08af6da7c49913764da7.js:1:93633)
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0
State: {"ckey":"its4fun","window":{"fancy":0,"locked":0}}
Nanotrasen (c) 2525-540
```

UPD: I did fix the issue for me. Leaving this here for anyone encountering the same problem.
As far as i can tell some temp files get corrupted after some trigger, most likely a github doing wonky stuff when switching branches and prs. After you uninstall your Byond, go to Documents, then Byond and wipe everything that you can, every single file in this folder, particularly the cfg and browserstorage, but wipe out everything just to be safe. This folder **does not** get deleted if you uninstall your byond, do it manually. After that you can reinstall your Byond and at this point the problem got fixed for me, hopefully this will help you too.
