### ISSUE TITLE
TGUI UnhandledRejection: Error: Out of memory

### ISSUE THREAD

**Issue by nightred** [tgstation/tgstation#56751]
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: Error: Out of memory
   at Anonymous function (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:209463)
   at l (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:191022)
   at o (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:190820)
   at Anonymous function (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:191462)
   at n (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:206996)
   at c (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:207209)
   at Anonymous function (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:76651)
   at r (https://tgstation13.download/byond/assets/d8/asset.d86ebb00ff72b0563fde3f3482d8d524.js:1:31224)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"themastere","window":{"fancy":0,"locked":0}}

Nanotrasen (c) 2525-2561

**Comment by stylemistake** [comment]
Perhaps you are indeed out of memory. Not sure why else it would pop up. Also, which UI?
