### ISSUE TITLE
Tablet bluescreen on main page

### ISSUE THREAD

**Issue by joybod** [tgstation/tgstation#59161]
Reporting client version: 513.1528

## Round ID:
[162393](https://scrubby.melonmesa.com/round/162393)

## Testmerges:
- [Fixes sound loops not well, stopping. ](https://www.github.com/tgstation/tgstation/pull/59138)
- [Popper Tooltips 2 (they don't crash this time)](https://www.github.com/tgstation/tgstation/pull/58980)

## Reproduction:

 I just had my tablet open, and it bluescreened. default home page relatively soon after round start.

"
![image](https://user-images.githubusercontent.com/25726397/118429311-04190e80-b697-11eb-8ba8-4b38900e98a7.png)

**Comment by joybod** [comment]
another one

ReferenceError: 'buttonContent' is undefined
   at n.render (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:343931)
   at ke (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:178084)
   at Se (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:178571)
   at Anonymous function (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:178782)
   at Fe (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:178760)
   at Te (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:179924)
   at Me (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:179763)
   at Fe (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:178740)
   at Anonymous function (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:178898)
   at Fe (http://127.0.0.1:64460/tmp32828/tgui-common.bundle.js:1:178876)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"joybod","interface":"NtosNetChat","window":{"key":"[0x21051705]-main","size":null,"fancy":1,"locked":1}}

**Comment by joybod** [comment]
seems to maybe be related to insulated gloves and their obstruction of tablets
