### ISSUE TITLE
Advanced camera console's search feature broken

### ISSUE THREAD

**Issue by Tastyfish** [tgstation/tgstation#63390]
## Round ID: N/A
Tested on current rev: master commit a1f62309d46477d0b91dbd2e9fa3c33f307d8797

## Testmerges:
N/A

## Reproduction:
The following reliably happens on a clean master pull:

1. Use an advanced camera console.
2. Press the *Jump to Camera* action button.
3. Time into the search bar and get a tgui bluescreen as follows:
```
TypeError: Unable to get property 'toLowerCase' of undefined or null reference
   at Anonymous function (http://127.0.0.1:57605/tmp21532/tgui.bundle.js:1:939540)
   at Anonymous function (http://127.0.0.1:57605/tmp21532/tgui.bundle.js:1:41117)
   at filter (http://127.0.0.1:57605/tmp21532/tgui.bundle.js:1:87906)
   at onInput (http://127.0.0.1:57605/tmp21532/tgui.bundle.js:1:939512)
   at t.handleInput (http://127.0.0.1:57605/tmp21532/tgui.bundle.js:1:372962)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"tastyfish","interface":"ListInput","window":{"key":"[0x2106e267]-main","size":null,"fancy":1,"locked":0}}
```

**Comment by Tastyfish** [comment]
Note that this is a `tgui_input_list` that takes an associated list as input. Odd because I don't see how it's any different than other examples that do work.

**Comment by Tastyfish** [comment]
I figured out it fails if any cameras in the world have a null c_tag, which is technically not guarenteed, but for example Icebox's morgue has a null c_tag. Will PR a check to fix it.
