### ISSUE TITLE
Pierrot's Throat(?) PANDEMIC error

### ISSUE THREAD

**Issue by mozi-h** [tgstation/tgstation#63880]
## Round ID:
176123 (Terry 🇪🇺)

## Reproduction:

Have 3 diseases, 2 cured, the uncured being Pierrot's Throat which I suspect may have caused the error. Put your blood into a PANDEMIC (I used the map-spawned one) and get the following on-screen error:

```
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Unable to get property 'symptoms' of undefined or null reference
   at s (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:1134618)
   at Ie (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:179720)
   at Te (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:179584)
   at Anonymous function (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:179720)
   at Me (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:180768)
   at Te (http://127.0.0.1:11950/tmp14988/tgui.bundle.js:1:180607)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"tetrahedris","interface":"Pandemic","window":{"key":"[0x200fc7d]-main","size":null,"fancy":1,"locked":1}}
```

**Comment by SuperNovaa41** [comment]
https://github.com/tgstation/tgstation/pull/63448 didn't fix the issue it seems

**Comment by jlsnow301** [comment]
i am not able to replicate this issue
![1](https://user-images.githubusercontent.com/42397676/148458393-07ca2e1c-5f30-404f-aec0-2820b7b37104.png)

**Comment by JohnFulpWillard** [comment]
I cannot either
![image](https://user-images.githubusercontent.com/53777086/153115378-f01caca5-db2d-4eb4-9d1a-b4710738d2f6.png)

**Comment by mozi-h** [comment]
Somehow probably work again - Cannot reproduce
