### ISSUE TITLE
Tryed to open character menu and got this

### ISSUE THREAD

**Issue by DasGravity** [tgstation/tgstation#64081]


Character Preferences

×

Gravity Jhonson

An-Binyaar

Ismael Robinson

Buy BYOND premium for more slots!

Character

Occupations

Antagonists

Quirks









Gravity Jhonson

Body type: 

 

Eye color: 

Change 

Facial hair gradient: 

 

Hair gradient: 

 

Skin tone: 

 

Age: 

Loading... 

Hardcore random: 

 

Random body: 



Randomize 

Security department: 

 

Uplink Spawn Location: 

 

 

ooooo      ooo     .     .oooooo.    .oooooo..o
`888b.     `8'   .o8    d8P'  `Y8b  d8P'    `Y8
 8 `88b.    8  .o888oo 888      888 Y88bo.
 8   `88b.  8    888   888      888  `"Y8888o.
 8     `88b.8    888   888      888      `"Y88b
 8       `888    888 . `88b    d88' oo     .d8P
o8o        `8    "888"  `Y8bood8P'  8""88888P'

 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:110598)
   at o (http://127.0.0.1:50647/tmp3024/tgui.bundle.js:1:64895)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"dasgravity","interface":"PreferencesMenu","window":{"key":"[0x210833cc]-main","size":null,"fancy":1,"locked":0}}

Nanotrasen (c) 2525-2561

**Comment by LemonInTheDark** [comment]
Do you have the round id this happen in?

**Comment by Mothblocks** [comment]
There's not really much to act on here.

The problem is the compiled data payload was malformed, probably just empty. Both of which are kind of hard to do anything about.

The only "fix" for this, at this point in time, is detecting that this error is going to happen (with a try/catch), then creating our own error page where we log what the compiled data was, just in case it is BYOND somehow messing up a json_encode or similar.

**Comment by itsmeow** [comment]
I made an error page for this here

https://github.com/BeeStation/BeeStation-Hornet/pull/8776/commits/6081ec4e24c54df1f524404cb391c050cea6f9c8
