### ISSUE TITLE
TGUI chat displaying NtOS error

### ISSUE THREAD

**Issue by R0merol** [tgstation/tgstation#65824]
Reporting client version: 514.1575

## Round ID:
[180805](https://scrubby.melonmesa.com/round/180805)

## Testmerges:
- [firelocks now automatically open once the alarms are cleared and fixed fire alarms not clearing](https://www.github.com/tgstation/tgstation/pull/65490)
- [Kapulimbs](https://www.github.com/tgstation/tgstation/pull/65523)

## Reproduction:
![image](https://user-images.githubusercontent.com/87220004/160955761-5f3c0957-1ba9-43b2-9e47-251233492e63.png)

Play in any /tg/ servers (Sybil, Terry, Manuel). Here's the NtOS error message on the chat window:
```
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: TypeError: Object doesn't support property or method 'startsWith'
   at t.canPageAcceptType (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:237906)
   at t.processBatch (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:248734)
   at t.tryFlushQueue (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:245545)
   at t.onStateLoaded (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:245458)
   at Anonymous function (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:236136)
   at s.dispatch (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:203933)
   at Anonymous function (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:235516)
   at l (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:185976)
   at o (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:185774)
   at Anonymous function (http://127.0.0.1:65519/tmp6900/tgui-panel.bundle.js:1:186420)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"frostyfaris","window":{"fancy":0,"locked":0}}

Nanotrasen (c) 2525-2562 
```

Switching to the old UI works. But the new UI is displaying this error always

**Comment by stylemistake** [comment]
@R0merol while nobody wants to debug this issue, try cleaning and resetting all Internet Explorer caches and preferences, see if that helps. Could be that the bug is triggered by stored chat logs.

**Comment by R0merol** [comment]
Oh hey! Clearing all the Internet Explorer caches does work. I'll keep that in mind whenever I see a NtOS error again. Thank you for your help!

**Comment by Mooshimi** [comment]
Related: #65824
