### ISSUE TITLE
Crew Monitoring Console doesn't load

### ISSUE THREAD

**Issue by labroske** [tgstation/tgstation#68942]
## Reproduction:

Left clicking the Crew Monitoring Console displays a window with this error:

TypeError: Unable to get property 'startsWith' of undefined or null reference
   at s (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:312939)
   at Be (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:179720)
   at Te (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:179584)
   at Anonymous function (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:179720)
   at De (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:180768)
   at Te (http://127.0.0.1:61396/tmp50080/tgui.bundle.js:1:180607)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"thekingwhowouldbeyellow","interface":"CrewConsole","window":{"key":"[0x21000434]-main","size":null,"fancy":1,"locked":0}}

**Comment by Mooshimi** [comment]
Are you sure this is the round number
