### ISSUE TITLE
Power monitoring computer crashes with bluescreen

### ISSUE THREAD

**Issue by lessthnthree** [tgstation/tgstation#70059]
A fatal exception has occurred at 002B:C562F1B7 in TGUI.

TypeError: Unable to get property 'supply' of undefined or null reference
   at p (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:1403528)
   at Be (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:179474)
   at Anonymous function (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:179720)
   at Te (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:179584)
   at Te (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:180573)
   at Le (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:179584)
   at Anonymous function (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:179742)
   at Le (http://127.0.0.1:52824/tmp14456/tgui.bundle.js:1:179720)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"lt3","interface":"PowerMonitor","window":{"key":"[0x2021b6c]-main","size":null,"fancy":1,"locked":1}}

![image](https://user-images.githubusercontent.com/83487515/191605806-05ca6324-e995-4607-92b3-240b1a97757a.png)

**Comment by jlsnow301** [comment]
I'm curious what circumstance lead to this error, as I wasn't able to reproduce it in test. 
I am going to push a PR that possibly fixes this in the meantime, so please let me know if you encounter this again.
