### ISSUE TITLE
TGUI error when trying to select occupations tab on 2nd or 3rd character in character setup.

### ISSUE THREAD

**Issue by Gavin-319** [tgstation/tgstation#70935]
Completely new here and IDK if I'm doing this right or not but here's the report copy-pasted from the error screen. 1st character is unaffected. 

UnhandledRejection: TypeError: Unable to get property 'Chief Engineer' of undefined or null reference
   at f (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:1366517)
   at Be (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179475)
   at Anonymous function (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179743)
   at Le (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179721)
   at De (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:180769)
   at Te (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:180608)
   at Le (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179585)
   at Anonymous function (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179743)
   at Le (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179721)
   at De (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:180769)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"traveler319","interface":"PreferencesMenu","window":{"key":"[0x2107ff27]-main","size":null,"fancy":1,"locked":0}}

UnhandledRejection: TypeError: Unable to get property 'Research Director' of undefined or null reference
   at f (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:1366517)
   at Be (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179475)
   at Anonymous function (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179743)
   at Le (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179721)
   at De (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:180769)
   at Te (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:180608)
   at Le (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179585)
   at Anonymous function (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179743)
   at Le (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:179721)
   at De (https://tgstation13.download/byond/assets/5e/asset.5e453a3ff0cfe8d8b4fb1985848c0be1.js:1:180769)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"traveler319","interface":"PreferencesMenu","window":{"key":"[0x2107ff27]-main","size":null,"fancy":1,"locked":0}}

**Comment by Mothblocks** [comment]
The round ID here is extremely important because some rounds have relevant test merges

Please include the round ID or this will be closed

**Comment by Gavin-319** [comment]
Round ID is 193482 right now on Sybil and it's still happening.
