### ISSUE TITLE
Debug component printer seems broken

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#71511]
Reporting client version: 514.1589

## Round ID:
[195013](https://scrubby.melonmesa.com/round/195013)

## Testmerges:
- [Revert "Unit tests radio, saymode, and language prefix keys"](https://www.github.com/tgstation/tgstation/pull/71474)

## Reproduction:

Spawn in /obj/machinery/debug_component_printer
Attempt to use it
```
TypeError: Can't call method on undefined
   at e.exports (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:75285)
   at e.exports (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:80022)
   at Anonymous function (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:70930)
   at entries (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:104895)
   at m (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:683895)
   at Be (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:179475)
   at Anonymous function (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:179743)
   at Le (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:179721)
   at De (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:180769)
   at Anonymous function (https://tgstation13.download/byond/assets/6e/asset.6e040a265cc425e9c8b2ae1dcf5c2930.js:1:179963)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"iain0","interface":"ComponentPrinter","window":{"key":"[0x201b324]-main","size":null,"fancy":1,"locked":1}}```

**Comment by NamelessFairy** [comment]
Caused by #69990

**Comment by GolfinhoVoador** [comment]
Still broken, but I wouldn't expect anyone to actually fix it

**Comment by iprice** [comment]
One year later, still broken.  Did circuits just instantly become abandonware?

**Comment by jlsnow301** [comment]
> but I wouldn't expect anyone to actually fix it

ping me in discord next time
