### ISSUE TITLE
Attempting to open App downloader on PDA causes a fatal exception

### ISSUE THREAD

**Issue by DustanHache** [tgstation/tgstation#73493]
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 ReferenceError: 'PC_device_theme' is undefined
   at t.NtosNetDownloader (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:1197583)
   at Be (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:179475)
   at Anonymous function (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:179743)
   at Le (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:179721)
   at Anonymous function (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:179663)
   at Le (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:179605)
   at je (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:186739)
   at ze (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:186978)
   at Anonymous function (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:1934399)
   at r (http://127.0.0.1:59893/tmp11784/tgui.bundle.js:1:250035)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E)
State: {"ckey":"doomlolcat","interface":"NtosNetDownloader","window":{"key":"[0x2102512d]-main","size":null,"fancy":1,"locked":1}}

**Comment by SyncIt21** [comment]
Probably broken by #73070. @JohnFulpWillard
