### ISSUE TITLE
Bug When Opening Donksoft Arcade On Everything That Runs NTOS (PDA Consoles Everything Else))

### ISSUE THREAD

**Issue by TTaxer** [tgstation/tgstation#73531]
ReferenceError: 'data' is undefined
   at t.NtosArcade (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:1158419)
   at Be (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:179475)
   at Anonymous function (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:179743)
   at Le (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:179721)
   at Anonymous function (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:181338)
   at Pe (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:181207)
   at Re (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:186472)
   at Anonymous function (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:182297)
   at Pe (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:182032)
   at je (http://127.0.0.1:50638/tmp3944/tgui.bundle.js:1:186821)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"taxer","interface":"NtosArcade","window":{"key":"[0x2100eed5]-main","size":null,"fancy":1,"locked":0}}

**Comment by JohnFulpWillard** [comment]
This was fixed

**Comment by JohnFulpWillard** [comment]
in https://github.com/tgstation/tgstation/pull/73602
