### ISSUE TITLE
NtOS "a fatal exception" Fancy chat wont load

### ISSUE THREAD

**Issue by AMARTI15** [tgstation/tgstation#75175]
Reporting client version: 514.1589

## Round ID:
205106

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: TypeError: Unable to get property 'unreadCount' of undefined or null reference
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:229785)
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:41113)
   at map (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:90914)
   at t.ChatTabs (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:229582)
   at Oe (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:174408)
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:177522)
   at Re (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:177298)
   at Le (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:178300)
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:176798)
   at Re (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:176337)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"aciiimart","window":{"fancy":0,"locked":0}}

UnhandledRejection: TypeError: Unable to get property 'unreadCount' of undefined or null reference
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:229785)
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:41113)
   at map (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:90914)
   at t.ChatTabs (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:229582)
   at Oe (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:174408)
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:177522)
   at Re (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:177298)
   at Le (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:178300)
   at Anonymous function (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:176798)
   at Re (https://tgstation13.download/byond/assets/ba/asset.ba28b53e444e4d256339b8c840dba4c6.js:1:176337)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"aciiimart","window":{"fancy":0,"locked":0}}

Nanotrasen (c) 2525-540 

My fancy chat won't load, hasn't since last night. I get the blue screen. Chat works with the old format only. fancy chat won't work on any tg servers for me, I opened up terry and basil to try and got the same error. Have attempted running byond in stable and beta versions, updated many times, "fix chat" doesn't work, "refresh TGUI" does not work, clearing cache does not work. It stopped working in the middle of a shift yesterday night, still won't load.

**Comment by 50Potas50water** [comment]
did you figure out how to fix this?
PDA was broken for me
did you mess with .NET at all? That's the only thing I could think of

**Comment by AMARTI15** [comment]
I haven't found out how to fix it. I've nearly stopped playing the game entirely because of it :(
