### ISSUE TITLE
TGUI is broken on Linux servers, works only some of the time

### ISSUE THREAD

**Issue by TheVekter** [tgstation/tgstation#75847]
## Round ID:

207554

## Reproduction:

Open any TGUI menu. Namely the character or game preference panels. 

We're already aware of this bug but it wasn't present anywhere in the issue tracker, so I'm putting it here to better track what's being done to actually fix it. Supposedly, it has something to do with MD5 hashing on the Linux server side of things. @Watermelon914 seems to know a bit about what's happening here.

```
UnhandledRejection: SyntaxError: Invalid character
   at Anonymous function (http://127.0.0.1:64275/tmp25472/tgui.bundle.js:1:110594)
   at o (http://127.0.0.1:64275/tmp25472/tgui.bundle.js:1:64891)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"vekter","interface":"PreferencesMenu","window":{"key":"[0x210036c5]-main","size":null,"fancy":1,"locked":1}}
```

Runtimes:

```
[[23:27:53] Runtime in code/modules/asset_cache/asset_cache_item.dm, line 43: invalid asset sent to asset cache](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x210036d4];viewruntime_backto=[0x21000963])
[[23:27:53] Runtime in code/modules/asset_cache/asset_list.dm, line 550: Cannot read 'html/font-awesome/webfonts/fa-...'.hash](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x210036e5];viewruntime_backto=[0x21000963])
[[23:27:53] Runtime in code/modules/asset_cache/transports/asset_transport.dm, line 74: Cannot read null.legacy](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x210036d2];viewruntime_backto=[0x21000963])
[[23:27:53] Runtime in code/__HELPERS/stack_trace.dm, line 4: Failed to strip chat_16x16.png: No such file or directory (os error 2) (code/modules/asset_cache/asset_list.dm:264)](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x210036f9];viewruntime_backto=[0x21000963])
[[23:27:53] Runtime in , line : bad icon operation](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21003700];viewruntime_backto=[0x21000963])
[[23:27:53] Runtime in code/modules/asset_cache/transports/asset_transport.dm, line 44: ERROR: Invalid asset: chat_16x16.png:/icon:/datum/asset_cache_item](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21003708];viewruntime_backto=[0x21000963])
[[23:27:53] Runtime in code/modules/asset_cache/asset_list.dm, line 290: Division by zero](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x2100370e];viewruntime_backto=[0x21000963])
[[23:28:18] Runtime in code/modules/asset_cache/asset_list.dm, line 336: Cannot read null.resource](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x210049fd];viewruntime_backto=[0x21000963])
[[23:32:20] Runtime in code/modules/tgui/tgui.dm, line 121: Cannot execute null.ui assets().](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21083e5e];viewruntime_backto=[0x21000963])
[[23:32:20] Runtime in code/modules/tgui/tgui.dm, line 252: Cannot read null.client](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21083e2b];viewruntime_backto=[0x21000963])
[[23:32:20] Runtime in code/controllers/subsystem/tgui.dm, line 297: Cannot read null.tgui_open_uis](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21083e15];viewruntime_backto=[0x21000963])
[[23:32:21] Runtime in code/datums/callback.dm, line 109: bad proc](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21083ddb];viewruntime_backto=[0x21000963])
[[23:42:33] Runtime in code/_onclick/hud/alert.dm, line 371: Cannot read null.comp_lookup](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21085f20];viewruntime_backto=[0x21000963])
[[23:43:14] Runtime in code/controllers/subsystem/movement/movement_types.dm, line 115: Cannot read null.visual_delay](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x21085af4];viewruntime_backto=[0x21000963])
[[23:46:55] Runtime in code/controllers/subsystem/movement/movement.dm, line 102: type mismatch: null -= /datum/move_loop/move (/datum/move_loop/move)](http://127.0.0.1:64275/tmp25472/8fedbdda.htm?_src_=holder;admin_token=59239910901623462305511010143660189;viewruntime=[0x2107d19a];viewruntime_backto=[0x21000963])
```

**Comment by Watermelon914** [comment]
It's an asset transfer problem since the md5 hash for each asset isn't getting generated properly. Check the runtimes for the round id and you'll see the errors related to it.

**Comment by TheVekter** [comment]
#75835 might fix this, but it's TMed on Campbell and doesn't seem to be doing anything, either because the code's not functional or it doesn't fix the problem.

**Comment by TheVekter** [comment]
I think Watermelon went to bed, basically whatever is wrong is BYOND's fault (natch) but #75848 appears to both fix the fcopy issue and whatever the hell caused this, it's a good bandaid until Lummox fixes it proper.
