### ISSUE TITLE
NTOS error in ClothesMate colour selection UI

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#77291]
Reporting client version: 514.1589

## Round ID:
211561

## Reproduction:

Spawn an /obj/machinery/vending/clothing
Set its onstation=0 if that helps you
Pick any item's colour selector
NTOS bluescreen:

```
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Unable to get property 'icon_states' of undefined or null reference
   at h (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:887084)
   at Be (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:179475)
   at Anonymous function (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:179743)
   at Le (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:179721)
   at Me (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:180769)
   at Ae (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:180608)
   at Le (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:179585)
   at Ae (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:180574)
   at Le (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:179585)
   at Anonymous function (http://127.0.0.1:51106/tmp36272/tgui.bundle.js:1:179743)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0)
State: {"ckey":"iain0","interface":"GreyscaleModifyMenu","window":{"key":"[0x20026bb]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-540 
```

**Comment by Sealed101** [comment]
Duplicate of #77246
