### ISSUE TITLE
[<TGMC>] Error when opening gear tab on character customization

### ISSUE THREAD

**Issue by BielNS06** [tgstation/tgstation#79215]
## Reproduction:

open character customization, go to gear tab

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Não é possível obter a propriedade 'cost' de referência indefinida ou nula
   at Anonymous function (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:624969)
   at t.GearCustomization (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:624939)
   at Be (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:161096)
   at Anonymous function (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:161364)
   at Le (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:161342)
   at Me (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:162195)
   at Le (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:161206)
   at Me (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:162195)
   at Le (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:161206)
   at Te (http://127.0.0.1:57555/tmp3476/tgui.bundle.js:1:162390)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"robloxdown2021","interface":"PlayerPreferences","window":{"key":"[0x21023438]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-2563

**Comment by Jacquerel** [comment]
You're probably better off reporting this error to TGMC, it's likely related to their UI code and not anything on this repo.
