### ISSUE TITLE
Quirk Menu NTOS bluescreens the character preference window.

### ISSUE THREAD

**Issue by Jezzared** [tgstation/tgstation#80011]
## Testmerges:
[#79971: 'Blood brothers is now a single person conversion antagonist' by Mothblocks at commit 57777bf9df](https://www.github.com/tgstation/tgstation/pull/79971)
[#79854: 'Changes Virology Rather Than Killing It' by Higgin at commit d735e8afa7](https://www.github.com/tgstation/tgstation/pull/79854)
[#79974: 'Drops ie8 support' by jlsnow301 at commit 99757a8914](https://www.github.com/tgstation/tgstation/pull/79974)

## Reproduction:

Open prefs to check on my quirks because a new one got added that changed one of the ones my characters uses.
Open the quirks menu.

Bluescreen.

```
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 TypeError: Object doesn't support property or method 'remove'
   at Anonymous function (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:178:4878)
   at an (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:84896)
   at xt (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:85013)
   at k (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:178:4829)
   at Ke (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:73428)
   at Ke (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:73585)
   at Ke (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:73377)
   at Ke (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:73585)
   at tt (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:73699)
   at Ke (https://tgstation13.download/byond/assets/af/asset.afbe5100cd524e1dddcc0056e36b0fed.js:1:73362)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"jezzared","interface":"PreferencesMenu","window":{"key":"[0x210a1642]-main","size":null,"fancy":1,"locked":0}}
```

**Comment by jlsnow301** [comment]
Thank you, noted. This was fixed in [8bef693](https://github.com/tgstation/tgstation/pull/79974/commits/8bef693e672b6c7ba83f83e9a512e75aa63b84f8)
