### ISSUE TITLE
Emojipedia locks up for a while then TGUI bluescreens

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#80282]
Reporting client version: 514.1589

## Round ID:
[220395](https://scrubby.melonmesa.com/round/220395)

## Testmerges:
- [Reworks morgue trays. Freezers and morgue trays now have their own internal air. Organs no longer take damage when below freezing temperatures.](https://www.github.com/tgstation/tgstation/pull/80219)

## Reproduction:

Spawn in a PDA, load emojipedia, open it
```
Error: Minified React error #137; visit https://reactjs.org/docs/error-decoder.html?invariant=137&args[]=img for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at Te (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:15052)
   at Yu (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:93155)
   at _l (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:116296)
   at El (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:116054)
   at td (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:115921)
   at Yi (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:115774)
   at Tl (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:112772)
   at Wr (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:48847)
   at cr (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:110061)
   at Ji (https://tgstation13.download/byond/assets/2f/asset.2f113533f6a352f467f47ee045caf8b0.js:9:127951)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0)
State: {"ckey":"iain0","interface":"NtosEmojipedia","window":{"key":"[0x201f5ea]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-540 
```

**Comment by MrStonedOne** [comment]
unminified error message: 
```
img is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
```

**Comment by san7890** [comment]
@jlsnow301
