### ISSUE TITLE
adding circuit components from inside the circuit bluescreens

### ISSUE THREAD

**Issue by NoodleNoms** [tgstation/tgstation#80491]
Reporting client version: 515.1620

## Issue Summary

after you use a circuit on a component printer you are supposed to be able to go into it and print the parts from the circuit itself to save time printing them all individualy but for the past week or so doing that and trying to open the menu that lets you add components just bluesceens the menu

## Round ID:
[220847](https://scrubby.melonmesa.com/round/220847)

## Testmerges:
- [Increase TGUI connection lost threshold](https://www.github.com/tgstation/tgstation/pull/80304)
- [Refactors TS in Box component](https://www.github.com/tgstation/tgstation/pull/80368)

## Reproduction:
get circuit. use circuit on component printer. open circuit. click the "+" near the name part in the topleft. bluescreen.

here is what it prints out 
`UnhandledRejection:` TypeError: Unable to get property 'component' of undefined or null reference
   at u.render (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:279:349338)
   at hl (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:80524)
   at $c (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:80374)
   at _u (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:119950)
   at vu (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:114785)
   at id (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:114719)
   at xs (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:114572)
   at hu (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:111598)
   at co (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:48533)
   at Bi (https://tgstation13.download/byond/assets/1d/asset.1d51fb6d98092a556e01bc323e346c37.js:9:108897)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"noodlenoms","interface":"IntegratedCircuit","window":{"key":"[0x200b117]-main","size":null,"fancy":1,"locked":0}}`

**Comment by SyncIt21** [comment]
Duplicate #80437
