### ISSUE TITLE
Biogenerator tabs cause bluescreen.

### ISSUE THREAD

**Issue by DustanHache** [tgstation/tgstation#80838]
## Issue Summary
Opening some menus, namely the biogenerator tabs, causes NTOS bluescreen. Error code as follows:
   at il (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:65859)
   at fl (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:77347)
   at _u (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:119862)
   at vu (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:114781)
   at id (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:114715)
   at ds (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:114568)
   at hu (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:111594)
   at ia (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:48529)
   at Dl (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:111916)
   at gr (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:16283)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"doomlolcat","interface":"Biogenerator","window":{"key":"[0x20075cd]-main","size":null,"fancy":1,"locked":1}}

<!--- **INCLUDE THE ROUND ID**
If you discovered this issue from playing tgstation hosted servers:
[Round ID]: # 221771 Bagil

## Reproduction:
Literally just open the biogenerator tabs for fertilizer or other products.

**Comment by jlsnow301** [comment]
Fixed in #80815 and confirmed on manuel live
