### ISSUE TITLE
Spare safe code is unusable.

### ISSUE THREAD

**Issue by Kitfox88** [tgstation/tgstation#80834]
Reporting client version: 514.1589

## Issue Summary

Was appointed acting captain, HoP offered to take it off my hands. Gave him the pack containing the safe code. When they opened it, it was a bluescreen. When I tried to read it, same deal.

## Round ID:
[221773](https://scrubby.melonmesa.com/round/221773)

## Testmerges:
- [tgui now disables topics on world reboot, should fix reconnects randomly failing](https://www.github.com/tgstation/tgstation/pull/80779)

## Reproduction:

Give biscuit pack to HoP. Watch as paper turns into a bluescreen error.

A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at ii (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:65388)
   at j.useState (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:25:6454)
   at K.render (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:290:3057)
   at hl (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:80520)
   at $c (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:80370)
   at _u (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:119946)
   at vu (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:114781)
   at id (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:114715)
   at ds (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:114568)
   at hu (https://tgstation13.download/byond/assets/9c/asset.9c0c02ac60408ef9feb2d457c5f48622.js:9:111594)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"kitfox88","interface":"PaperSheet","window":{"key":"[0x201faa7]-main","size":null,"fancy":0,"locked":1}}

**Comment by PapaMichae1** [comment]
Duplicate https://github.com/tgstation/tgstation/issues/80814

**Comment by DustanHache** [comment]
this is more recent, and I fear is post merge that closed the previous.

**Comment by PapaMichae1** [comment]
Servers update twice a day, not after each PR

**Comment by Kitfox88** [comment]
Oh, sorry for the dupe, probably should have checked, my bad.

**Comment by FlufflesTheDog** [comment]
> You can check the changelog to see if a particular PR has been merged yet on a server

Changelogs also don't update until a bit after that, so the most reliable way is to check the master commit in "show server revision" to see if its dated before or after a certain pr was merged.
