### ISSUE TITLE
TGUI Crash on startup

### ISSUE THREAD

**Issue by AsrielFBI** [tgstation/tgstation#81879]
## Issue Summary
Everytime I join ANY tg based instance server, I just get this error on my screen:

TypeError: The object does not accept the property or method 'startsWith'
   at p (http://127.0.0.1:33828/tgui-panel.bundle.js:191:1065)
   at nt (http://127.0.0.1:33828/tgui-panel.bundle.js:161:7012)
   at Se.processBatch (http://127.0.0.1:33828/tgui-panel.bundle.js:161:7377)
   at Se.tryFlushQueue (http://127.0.0.1:33828/tgui-panel.bundle.js:161:3364)
   at Se.mount (http://127.0.0.1:33828/tgui-panel.bundle.js:161:3211)
   at ge.componentDidMount (http://127.0.0.1:33828/tgui-panel.bundle.js:171:649)
   at cc (http://127.0.0.1:33828/tgui-panel.bundle.js:9:105500)
   at Hc (http://127.0.0.1:33828/tgui-panel.bundle.js:9:105283)
   at Ni (http://127.0.0.1:33828/tgui-panel.bundle.js:9:104821)
   at Va (http://127.0.0.1:33828/tgui-panel.bundle.js:9:114766)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"asrielfbi","window":{"fancy":0,"locked":0}}

Nanotrasen (c) 2525-540 

![imagen](https://github.com/tgstation/tgstation/assets/56162938/f1a1d780-020d-44e3-a4f8-9e3f298e0f37)

This includes LOCALHOST TG BASED Servers like tgstation.
It all worked fine until it just didnt, The only change I had on my computer was changing my 2 monitors from 1080p to 2k, but it should NOT matter at all.

Note: I also tried lots of different byond versions suggested by people from discord, none worked.
Note2: Also tried cleaning cache each time, did not work.

## Reproduction:
>Install byond
>Change to beta version
>Join any TG Based server like tgstation, bubbers, shiptest, etc...
>Get the error.

**Comment by SyncIt21** [comment]
Is this still occurring?

Byond latest stable version is 515.1633. Try upgrading to that and check if the issue persists

**Comment by AsrielFBI** [comment]
> Is this still occurring?
> 
> Byond latest stable version is 515.1633. Try upgrading to that and check if the issue persists

Still same problem.
