### ISSUE TITLE
Paper NTOS error :(

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#82155]
Reporting client version: 515.1633

## Issue Summary
Saving changes to paper with any pen causes the paper screen to display a NTOS error.

## Round ID:
[225894](https://scrubby.melonmesa.com/round/225894)

## Testmerges:
- [Moves lua off of the timer subsystem and onto its own internal scheduler.](https://www.github.com/tgstation/tgstation/pull/82131)

## Reproduction:

1. Hold a paper and a pen.
2. Write on the paper with the pen.
3. Save the change on the paper.
4. Observe NTOS error

## Logs

ooooo      ooo     .     .oooooo.    .oooooo..o
`888b.     `8'   .o8    d8P'  `Y8b  d8P'    `Y8
 8 `88b.    8  .o888oo 888      888 Y88bo.
 8   `88b.  8    888   888      888  `"Y8888o.
 8     `88b.8    888   888      888      `"Y88b
 8       `888    888 . `88b    d88' oo     .d8P
o8o        `8    "888"  `Y8bood8P'  8""88888P'

 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 SyntaxError: Syntax error in regular expression
Please report this to https://github.com/markedjs/marked.
   at q (http://127.0.0.1:60766/tgui.bundle.js:318:167882)
   at Oe.emStrong (http://127.0.0.1:60766/tgui.bundle.js:322:14314)
   at Me (http://127.0.0.1:60766/tgui.bundle.js:322:29708)
   at Oe.inlineTokens (http://127.0.0.1:60766/tgui.bundle.js:322:31373)
   at Oe.lex (http://127.0.0.1:60766/tgui.bundle.js:322:26193)
   at Pe.lex (http://127.0.0.1:60766/tgui.bundle.js:322:31458)
   at Anonymous function (http://127.0.0.1:60766/tgui.bundle.js:322:40521)
   at Se (http://127.0.0.1:60766/tgui.bundle.js:322:40694)
   at B.runMarkedDefault (http://127.0.0.1:60766/tgui.bundle.js:286:7268)
   at B.formatAndProcessRawText (http://127.0.0.1:60766/tgui.bundle.js:286:7454)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PaperSheet","window":{"key":"[0x20032fd]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-540

**Comment by raffclar** [comment]
What sort of text were you trying to type? The log you posted has some weird characters

**Comment by raffclar** [comment]
Possibly related:
https://github.com/tgstation/tgstation/issues/83647
