### ISSUE TITLE
Biogenerator: Switching category tabs goes to NtOS crash handler

### ISSUE THREAD

**Issue by OverwatchVoice** [tgstation/tgstation#83583]
Reporting client version: 515.1636

## Issue Summary

Self-explanatory. Crash log below.
![obrazek](https://github.com/tgstation/tgstation/assets/39193093/66137595-57b3-4924-b9a1-efc042b180a3)
`Error: Minified React error #300; visit https://reactjs.org/docs/error-decoder.html?invariant=300 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at rl (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:65855)
   at dl (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:77343)
   at ju (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:119859)
   at vu (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:114778)
   at rd (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:114712)
   at gs (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:114565)
   at Ml (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:110777)
   at fu (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:111650)
   at xa (http://127.0.0.1:63581/asset.ab02120f2f42ba7fdf2c7d5eef1e857b.js:9:48525)
`
## Round ID:
[229692](https://scrubby.melonmesa.com/round/229692)

## Testmerges:
- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Fixes free chemsplosion reagent purging by replacing it with the same thing but dangerous](https://www.github.com/tgstation/tgstation/pull/83195)
- [STATION TRAIT GAMEMODE: Station-Wide Background Checks](https://www.github.com/tgstation/tgstation/pull/83307)

## Reproduction:

1. Open biogen UI.
2. At top of UI, attempt to select "Chemicals" or "Materials".

**Comment by the-orange-cow** [comment]
Same as https://github.com/tgstation/tgstation/issues/83571
