### ISSUE TITLE
Malf UI is affected by uplink ui update

### ISSUE THREAD

**Issue by delingar** [tgstation/tgstation#85999]
### Client Version:

515.1637

### Issue Summary:

Malf Module UI is affected by uplink UI update, that is not looks good. Picked modules do not disappear.
![image](https://github.com/user-attachments/assets/7a038603-1e4c-4e84-b21b-3e22571eaca9)

### Reproduction Steps:

1. Get malf
2. Check modules ui.
3. Get your eyes tortured

**Comment by MrMelbert** [comment]
Abductors are probably also effective, all 3 use the `GenericUplink` ui component

**Comment by Syilumi** [comment]
this has also caused it to randomly NTOS screen for me i think
`TypeError: Unable to get property 'length' of undefined or null reference
   at b (http://127.0.0.1:55494/tgui.bundle.js:291:92332)
   at $c (http://127.0.0.1:55494/tgui.bundle.js:9:67891)
   at bs (http://127.0.0.1:55494/tgui.bundle.js:9:124452)
   at No (http://127.0.0.1:55494/tgui.bundle.js:9:119885)
   at bh (http://127.0.0.1:55494/tgui.bundle.js:9:119819)
   at hc (http://127.0.0.1:55494/tgui.bundle.js:9:119668)
   at du (http://127.0.0.1:55494/tgui.bundle.js:9:115689)
   at Ed (http://127.0.0.1:55494/tgui.bundle.js:9:114595)
   at H (http://127.0.0.1:55494/tgui.bundle.js:33:1657)
   at se (http://127.0.0.1:55494/tgui.bundle.js:33:2046)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {"ckey":"simbolitis","interface":"AntagInfoMalf","window":{"key":"[0x210d31d0]-main","size":null,"fancy":1,"locked":0}}` is the whole.. error thing
