### ISSUE TITLE
NTOS issue when opening character set up

### ISSUE THREAD

**Issue by Zargoar** [tgstation/tgstation#86282]
Reporting client version: 515.1643

## Issue Summary
User observes big ugly NTOS text string when attempting to set up character.

## Round ID:
[236311](https://scrubby.melonmesa.com/round/236311)

## Testmerges:
- [[tm]Revert "Refactor Stat Panel styles and more TGUI-like appearance"](https://www.github.com/tgstation/tgstation/pull/85392)

## Reproduction:

1- Join server.
2- Select 'character setup'.
3- Observe NTOS text string.

<details open>
  <summary>Error String</summary>
ooooo      ooo     .     .oooooo.    .oooooo..o
`888b.     `8'   .o8    d8P'  `Y8b  d8P'    `Y8
 8 `88b.    8  .o888oo 888      888 Y88bo.
 8   `88b.  8    888   888      888  `"Y8888o.
 8     `88b.8    888   888      888      `"Y88b
 8       `888    888 . `88b    d88' oo     .d8P
o8o        `8    "888"  `Y8bood8P'  8""88888P'

 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: SyntaxError: Syntax error
   at yt (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:112030)
   at Anonymous function (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:113868)
   at X (http://127.0.0.1:53775/asset.c57da3214a7c23eeeead5dfcb5917441.js:410:48502)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; wbx 1.0.0; Zoom 3.6.0)
State: {"ckey":"leifnobody","interface":"PreferencesMenu","window":{"key":"[0x210a2e0e]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-540 
</details>

![image](https://github.com/user-attachments/assets/8280358e-d5af-4ebb-92cc-1d4163e78be9)

**Comment by lessthnthree** [comment]
@Zargoar I believe this was fixed, adding to cleanup. Let us know if you still get it.
