### ISSUE TITLE
Paper has regexp issue with strings containing _

### ISSUE THREAD

**Issue by iprice** [tgstation/tgstation#86761]
### Client Version:

515.1641

### Issue Summary:

Grab a paper and a pen
Write _a on the paper
Save it
Bluescreen

(seems underscore followed by any character, but not the other way around)

```
SyntaxError: Syntax error in regular expression
Please report this to https://github.com/markedjs/marked.
   at Ae (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:410:121190)
   at Ze.emStrong (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:416:59632)
   at lt (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:416:75236)
   at Ze.inlineTokens (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:416:76923)
   at Ze.lex (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:416:71666)
   at it.lex (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:416:77019)
   at Anonymous function (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:416:86204)
   at st (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:416:86383)
   at fe.runMarkedDefault (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:310:7694)
   at fe.formatAndProcessRawText (http://127.0.0.1:53512/asset.5e3ed298281cdc9d114babc4c6f5201b.js:310:7900)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; Tablet PC 2.0)
State: {"ckey":"iain0","interface":"PaperSheet","window":{"key":"[0x201dabe]-main","size":null,"fancy":1,"locked":1}}

Nanotrasen (c) 2525-540 
```

### Round ID:

238327

### Test Merge Information:

- [[TM ONLY] Hijacked Revision Date for v3 TGS Api](https://www.github.com/tgstation/tgstation/pull/83227)
- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [GetFlatIcon improvements.](https://www.github.com/tgstation/tgstation/pull/86077)

### Reproduction Steps:

Spare box

**Comment by iprice** [comment]
If anyone's interested, this cropped up because a player sent a copy of a JSON circuit via fax machine, of which there are some variables like_this which results in this triggering the above.  I just reduced it down to a minimal reproduction.

**Comment by LemonInTheDark** [comment]
the error implies this is a problem with the markdown parsing library we use

**Comment by 00-Steven** [comment]
yeah this #80505 should have more info
