### ISSUE TITLE
NTOS error, starting today

### ISSUE THREAD

**Issue by K4rlox** [tgstation/tgstation#87537]
### Client Version:

515.1645

### Issue Summary:

Constantly keep getting NTOS error in fancy chat
wasnt getting any yesterday, been playing tg for a good while

Latest byond, windows is updated, tried turning on a vpn and connecting
clearing cache doesnt work
restarting pc doesnt work
noting again: this error started today, didnt get this yesterday

Full error:

ooooo      ooo     .     .oooooo.    .oooooo..o
`888b.     `8'   .o8    d8P'  `Y8b  d8P'    `Y8
 8 `88b.    8  .o888oo 888      888 Y88bo.
 8   `88b.  8    888   888      888  `"Y8888o.
 8     `88b.8    888   888      888      `"Y88b
 8       `888    888 . `88b    d88' oo     .d8P
o8o        `8    "888"  `Y8bood8P'  8""88888P'

 
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at Vi (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:124221)
   at _n (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:63317)
   at Mr (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:75605)
   at pc (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:120344)
   at cc (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:114479)
   at nf (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:114413)
   at Wi (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:114266)
   at sc (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:111300)
   at zo (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:48470)
   at of (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:115908)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"k4rl","window":{"fancy":0,"locked":0}}

Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
   at Vi (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:124221)
   at _n (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:63317)
   at Mr (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:75605)
   at pc (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:120344)
   at cc (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:114479)
   at nf (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:114413)
   at Wi (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:114266)
   at sc (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:111300)
   at zo (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:48470)
   at Anonymous function (http://127.0.0.1:54104/asset.2e063a3c640817be005d497a10bc3ad4.js:9:108885)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0)
State: {"ckey":"k4rl","window":{"fancy":0,"locked":0}}

Nanotrasen (c) 2525-540 

### Round ID:

240916

### Test Merge Information:

- [Adds new station map Nebulastation](https://www.github.com/tgstation/tgstation/pull/84826)
- [The death or internal/external organ pathing (ft. fixed fox ears and recoloring bodypart overlays with dye sprays)](https://www.github.com/tgstation/tgstation/pull/87434)
- [Add time dilation to hub status.](https://www.github.com/tgstation/tgstation/pull/87499)

### Reproduction Steps:

1. connect on latest byond
2. chat bluescreens

**Comment by Sadboysuss** [comment]
> noting again: this error started today, didnt get this yesterday
anything change on your end from yesterday? updated byond version? new software/hardware?

**Comment by K4rlox** [comment]
> > noting again: this error started today, didnt get this yesterday
> 
> anything change on your end from yesterday? updated byond version? new software/hardware?

NOTHING AT ALL

**Comment by jlsnow301** [comment]
> NTOS error in fancy chat

> :{"fancy":0,"locked":0}

wonder why reports this. maybe that's part of it?
