### ISSUE TITLE
Total chat death

### ISSUE THREAD

**Issue by cherdaq** [tgstation/tgstation#87633]
### Client Version:

515.1645

### Issue Summary:

The problem had started roughly at the same date as #87537 if not later than that, although the log seems to be different to the K4rlox's.
In fact, I had witnessed the problem starting right in the middle of a round on downstream server; the chat broke down unexpectedly, without seemingly any reason, and I had to revert to old UI until roundend. Haven't played SS13 much since then, but as I understand, it's like that on every TG-based server, like Skyrat or TG itself. The error message is also the same.
<details>
<summary>Log</summary>

```
A fatal exception has occurred at 002B:C562F1B7 in TGUI. The current application will be terminated. Send the copy of the following stack trace to an authorized Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: TypeError: Объект не поддерживает свойство или метод "startsWith"
   at v (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:179:1065)
   at te (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:149:6994)
   at mt.processBatch (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:149:7368)
   at mt.tryFlushQueue (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:149:3357)
   at mt.onStateLoaded (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:149:3269)
   at Anonymous function (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:167:3984)
   at M.dispatch (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:67:1814)
   at Anonymous function (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:167:3197)
   at ge (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:167:2315)
   at Anonymous function (http://127.0.0.1:53329/asset.cdfe1e3c83d196901c01afdc7dbcd8b9.js:167:1541)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Tablet PC 2.0; Zoom 3.6.0)
State: {"ckey":"gambe","window":{"fancy":0,"locked":0}}
```
</details>

### Reproduction Steps:

1. Bootup BYOND
2. Hop on a TG server (or any downstream for that matter)
3. Total chat death

**Comment by cherdaq** [comment]
> Potential fix for you

That and other things. Aside from doing multiple just-to-be-sure cleanups, I also: reinstalled BYOND completely, wiping both folders used for client and compiling; ran "sfc /scannow" in cmd; and rebooted my PC a few times.
![image](https://github.com/user-attachments/assets/31cf477f-8231-4221-ac01-2da2428d96e5)
To be honest, I'm amased that this is somehow the answer to that. Thank you very much for the pointer!
